# Generated by Django 4.1.4 on 2022-12-31 11:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('color_name', models.CharField(max_length=100)),
                ('color_hex_code', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('color_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
